theme: jekyll-theme-architect
# Google Analytics
google_analytics: UA-118330229-1
title: Luna multiplayer
description: Multiplayer mod for KSP
show_downloads: true
github:
  repo_url: https://github.com/LunaMultiplayer/LunaMultiplayer
servers:  
  #Tekbot
  release_url: https://cors-anywhere.herokuapp.com/http://212.48.114.221:8701/json
  debug_url: https://cors-anywhere.herokuapp.com/http://212.48.114.221:8751/json
  #Angryjoshi
  #release_url: https://cors-anywhere.herokuapp.com/http://lmp.anschuetznet.de:8701/json
  #debug_url: https://cors-anywhere.herokuapp.com/http://lmp.anschuetznet.de:8751/json
